# Generated by Django 5.2.7 on 2025-12-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_alter_question_answer_type"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="favourite_tests",
            field=models.ManyToManyField(
                blank=True, related_name="favoured_by", to="quiz.quiz"
            ),
        ),
    ]
