# Generated by Django 5.2.7 on 2025-12-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_remove_quiz_data_question_answeroption_quizattempt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="category",
            field=models.CharField(
                choices=[
                    ("general", "General Knowledge"),
                    ("science", "Science"),
                    ("history", "History"),
                    ("literature", "Literature"),
                    ("math", "Mathematics"),
                    ("sports", "Sports"),
                    ("entertainment", "Entertainment"),
                ],
                default="general",
                max_length=100,
            ),
        ),
    ]
