# Generated by Django 5.2.7 on 2025-12-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_quiz_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="answer_type",
            field=models.CharField(
                choices=[("single", "Single Choice"), ("multiple", "Multiple Choice")],
                default="single",
                max_length=50,
            ),
        ),
    ]
