# Generated by Django 5.2.7 on 2025-12-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_alter_question_answer_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizattempt",
            name="score",
            field=models.FloatField(default=0.0),
        ),
    ]
