# Generated by Django 5.2.7 on 2026-01-01 10:54

import django.db.models.deletion
import quiz.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0005_quizattempt_score"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=quiz.models.question_photo_path
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_quizzes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="quizattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("completed_at__isnull", True)),
                fields=("user", "quiz"),
                name="unique_quiz_per_user",
            ),
        ),
    ]
